# Generated by Django 3.2.3 on 2021-05-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Produto')),
                ('imagem', models.ImageField(upload_to='fileReceiver/')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
